# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        

fos_ck_editor:
    input_sync: true
    

    default_config: base_config
    configs:
        base_config:
            # autoGrow_onStartup: true
            # autoGrow_minHeight: 3000
            # full.colors: [ "TextColor", "BGColor" ]
            toolbar:
            # - { name: 'styles', items: [ 'Format'] }
            #    - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'CopyFormatting', 'RemoveFormat' ] }
               - { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline'] }
            #    - { name: 'colors', items: [ 'TextColor', 'BGColor' ] }
               - { name: 'colors', items: [ 'TextColor'] }
            #    - { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language' ] }
               - { name: 'paragraph', items: [ 'NumberedList', 'BulletedList', '-', 'Blockquote', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'] }
               - { name: 'links', items: [ 'Link', 'Unlink'] }
               - { name: 'insert', items: [ 'Table', 'Smiley'] }

    # plugins:
    #     colorbutton:
    #         path:   "/bundles/fosckeditor/plugins/colorbutton/"
    #         filename: "plugin.js"
               

            
