<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20201127113024 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE sheet ADD archived_at DATETIME DEFAULT NULL, CHANGE sub_category_id sub_category_id INT DEFAULT NULL, CHANGE origin_id origin_id INT DEFAULT NULL, CHANGE organization_id organization_id INT DEFAULT NULL, CHANGE front_author_id front_author_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE published_at published_at DATETIME DEFAULT NULL, CHANGE subtitle subtitle VARCHAR(255) DEFAULT NULL, CHANGE picture_filename picture_filename VARCHAR(255) DEFAULT NULL');
        // $this->addSql('ALTER TABLE sub_category RENAME INDEX uniq_bce3f79812469de2 TO IDX_BCE3F79812469DE2');
        $this->addSql('ALTER TABLE user CHANGE introduction introduction VARCHAR(255) DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(255) DEFAULT NULL, CHANGE token token VARCHAR(255) DEFAULT NULL, CHANGE password_requested_at password_requested_at DATETIME DEFAULT NULL, CHANGE picture_filename picture_filename VARCHAR(255) DEFAULT NULL, CHANGE direct_number direct_number VARCHAR(255) DEFAULT NULL, CHANGE pro_number pro_number VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE antenne CHANGE hours hours VARCHAR(255) DEFAULT NULL, CHANGE monday_am_open monday_am_open TIME DEFAULT NULL, CHANGE monday_am_close monday_am_close TIME DEFAULT NULL, CHANGE monday_pm_open monday_pm_open TIME DEFAULT NULL, CHANGE monday_pm_close monday_pm_close TIME DEFAULT NULL, CHANGE tuesday_am_open tuesday_am_open TIME DEFAULT NULL, CHANGE tuesday_am_close tuesday_am_close TIME DEFAULT NULL, CHANGE tuesday_pm_open tuesday_pm_open TIME DEFAULT NULL, CHANGE tuesday_pm_close tuesday_pm_close TIME DEFAULT NULL, CHANGE wednesday_am_open wednesday_am_open TIME DEFAULT NULL, CHANGE wednesday_am_close wednesday_am_close TIME DEFAULT NULL, CHANGE wednesday_pm_open wednesday_pm_open TIME DEFAULT NULL, CHANGE wednesday_pm_close wednesday_pm_close TIME DEFAULT NULL, CHANGE thursday_am_open thursday_am_open TIME DEFAULT NULL, CHANGE thursday_am_close thursday_am_close TIME DEFAULT NULL, CHANGE thursday_pm_open thursday_pm_open TIME DEFAULT NULL, CHANGE thursday_pm_close thursday_pm_close TIME DEFAULT NULL, CHANGE friday_am_open friday_am_open TIME DEFAULT NULL, CHANGE friday_am_close friday_am_close TIME DEFAULT NULL, CHANGE friday_pm_open friday_pm_open TIME DEFAULT NULL, CHANGE saturday_am_open saturday_am_open TIME DEFAULT NULL, CHANGE saturday_am_close saturday_am_close TIME DEFAULT NULL, CHANGE saturday_pm_open saturday_pm_open TIME DEFAULT NULL, CHANGE saturday_pm_close saturday_pm_close TIME DEFAULT NULL, CHANGE sunday_am_open sunday_am_open TIME DEFAULT NULL, CHANGE sunday_am_close sunday_am_close TIME DEFAULT NULL, CHANGE sunday_pm_open sunday_pm_open TIME DEFAULT NULL, CHANGE sunday_pm_close sunday_pm_close TIME DEFAULT NULL, CHANGE friday_pm_close friday_pm_close TIME DEFAULT NULL');
        $this->addSql('ALTER TABLE document CHANGE sub_category_id sub_category_id INT DEFAULT NULL, CHANGE front_author_id front_author_id INT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT NULL, CHANGE front front TINYINT(1) DEFAULT NULL, CHANGE published_at published_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE organization CHANGE last_author_id last_author_id INT DEFAULT NULL, CHANGE address address VARCHAR(255) DEFAULT NULL, CHANGE city city VARCHAR(255) DEFAULT NULL, CHANGE postcode postcode INT DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE website website VARCHAR(255) DEFAULT NULL, CHANGE logo_filename logo_filename VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE interlocutor CHANGE last_author_id last_author_id INT DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(255) DEFAULT NULL, CHANGE email email VARCHAR(255) DEFAULT NULL, CHANGE pro_number pro_number VARCHAR(255) DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE attachment CHANGE title title VARCHAR(255) DEFAULT NULL, CHANGE file file VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE header CHANGE title title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE paragraph CHANGE title title VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE section CHANGE title title VARCHAR(255) DEFAULT NULL');
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE antenne CHANGE hours hours VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE monday_am_open monday_am_open TIME DEFAULT \'NULL\', CHANGE monday_am_close monday_am_close TIME DEFAULT \'NULL\', CHANGE monday_pm_open monday_pm_open TIME DEFAULT \'NULL\', CHANGE monday_pm_close monday_pm_close TIME DEFAULT \'NULL\', CHANGE tuesday_am_open tuesday_am_open TIME DEFAULT \'NULL\', CHANGE tuesday_am_close tuesday_am_close TIME DEFAULT \'NULL\', CHANGE tuesday_pm_open tuesday_pm_open TIME DEFAULT \'NULL\', CHANGE tuesday_pm_close tuesday_pm_close TIME DEFAULT \'NULL\', CHANGE wednesday_am_open wednesday_am_open TIME DEFAULT \'NULL\', CHANGE wednesday_am_close wednesday_am_close TIME DEFAULT \'NULL\', CHANGE wednesday_pm_open wednesday_pm_open TIME DEFAULT \'NULL\', CHANGE wednesday_pm_close wednesday_pm_close TIME DEFAULT \'NULL\', CHANGE thursday_am_open thursday_am_open TIME DEFAULT \'NULL\', CHANGE thursday_am_close thursday_am_close TIME DEFAULT \'NULL\', CHANGE thursday_pm_open thursday_pm_open TIME DEFAULT \'NULL\', CHANGE thursday_pm_close thursday_pm_close TIME DEFAULT \'NULL\', CHANGE friday_am_open friday_am_open TIME DEFAULT \'NULL\', CHANGE friday_am_close friday_am_close TIME DEFAULT \'NULL\', CHANGE friday_pm_open friday_pm_open TIME DEFAULT \'NULL\', CHANGE saturday_am_open saturday_am_open TIME DEFAULT \'NULL\', CHANGE saturday_am_close saturday_am_close TIME DEFAULT \'NULL\', CHANGE saturday_pm_open saturday_pm_open TIME DEFAULT \'NULL\', CHANGE saturday_pm_close saturday_pm_close TIME DEFAULT \'NULL\', CHANGE sunday_am_open sunday_am_open TIME DEFAULT \'NULL\', CHANGE sunday_am_close sunday_am_close TIME DEFAULT \'NULL\', CHANGE sunday_pm_open sunday_pm_open TIME DEFAULT \'NULL\', CHANGE sunday_pm_close sunday_pm_close TIME DEFAULT \'NULL\', CHANGE friday_pm_close friday_pm_close TIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE attachment CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE file file VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE document CHANGE sub_category_id sub_category_id INT DEFAULT NULL, CHANGE front_author_id front_author_id INT DEFAULT NULL, CHANGE status status VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE front front TINYINT(1) DEFAULT \'NULL\', CHANGE published_at published_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE header CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE interlocutor CHANGE last_author_id last_author_id INT DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE pro_number pro_number VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE organization CHANGE last_author_id last_author_id INT DEFAULT NULL, CHANGE address address VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE city city VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE postcode postcode INT DEFAULT NULL, CHANGE phone_number phone_number VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE email email VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE website website VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE logo_filename logo_filename VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE updated_at updated_at DATETIME DEFAULT \'NULL\'');
        $this->addSql('ALTER TABLE paragraph CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE section CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE sheet DROP archived_at, CHANGE sub_category_id sub_category_id INT DEFAULT NULL, CHANGE origin_id origin_id INT DEFAULT NULL, CHANGE organization_id organization_id INT DEFAULT NULL, CHANGE front_author_id front_author_id INT DEFAULT NULL, CHANGE title title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE status status VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE published_at published_at DATETIME DEFAULT \'NULL\', CHANGE subtitle subtitle VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE picture_filename picture_filename VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE sub_category RENAME INDEX idx_bce3f79812469de2 TO UNIQ_BCE3F79812469DE2');
        $this->addSql('ALTER TABLE user CHANGE introduction introduction VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE phone_number phone_number VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE token token VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE password_requested_at password_requested_at DATETIME DEFAULT \'NULL\', CHANGE picture_filename picture_filename VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE direct_number direct_number VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`, CHANGE pro_number pro_number VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'NULL\' COLLATE `utf8mb4_unicode_ci`');
    }
}
